### Creating Numpy array from Python lists 


In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
[3.14, 3, 4, 2]

[3.14, 3, 4, 2]

In [5]:
np.array([3.14, 4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
a1 = np.array([1, 2, 3, 4])

In [11]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [15]:
type(a2)

numpy.ndarray

In [16]:
a2.shape

(2, 3)

In [17]:
a2.ndim

2

In [18]:
a2.dtype

dtype('int64')

In [19]:
a2.size

6

### Creating Numpy Arrays from Scratch

In [ ]:
np.zeros([2,4], dtype = int)

dtype('int64')

In [ ]:
np.ones([3,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.arange(0, 10, 2, dtype = float)

array([0., 2., 4., 6., 8.])

In [34]:
np.full([3, 5], 10, dtype = float)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [37]:
np.linspace(0, 1, 5, dtype = float)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random 

In [56]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [58]:
np.random.normal(0, 1, [3,4])

array([[ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852]])

In [63]:
np.random.rand(4,4)

array([[0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347],
       [0.50962438, 0.05571469, 0.45115921, 0.01998767],
       [0.44171092, 0.97958673, 0.35944446, 0.48089353]])

In [62]:
np.random.randint(0, 10, [3,4])

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]], dtype=int32)

### Array Indexing & Slicing

#### One-dimensional subarray

In [64]:
x1 = np.random.randint(20, size = 6)

In [65]:
x1 

array([ 2,  3,  3, 18, 14,  3], dtype=int32)

In [68]:
x1[4], x1[0], x1[-1]

(np.int32(14), np.int32(2), np.int32(3))

#### Multi-dimensional array

In [69]:
x2 = np.random.randint(10, size = (3,4))

In [70]:
x2

array([[4, 1, 2, 9],
       [1, 4, 6, 8],
       [2, 3, 0, 0]], dtype=int32)

In [75]:
x2[2, -1], x2[0, 0]

(np.int32(0), np.int32(4))

In [76]:
x2[1, 2] = 10

In [77]:
x2

array([[ 4,  1,  2,  9],
       [ 1,  4, 10,  8],
       [ 2,  3,  0,  0]], dtype=int32)

#### Slicing

In [78]:
x1

array([ 2,  3,  3, 18, 14,  3], dtype=int32)

In [80]:
x1[0: 3]

array([2, 3, 3], dtype=int32)

In [81]:
x1[2:4]

array([ 3, 18], dtype=int32)

In [82]:
x1[::2]

array([ 2,  3, 14], dtype=int32)

In [83]:
x2

array([[ 4,  1,  2,  9],
       [ 1,  4, 10,  8],
       [ 2,  3,  0,  0]], dtype=int32)

In [84]:
x2[:2,:3]

array([[ 4,  1,  2],
       [ 1,  4, 10]], dtype=int32)

In [85]:
x2[:2, :4]

array([[ 4,  1,  2,  9],
       [ 1,  4, 10,  8]], dtype=int32)

### Reshape of Arrays & Transpose

In [ ]:
grid = np.arange(1,10)
grid.shape

(9,)

In [88]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
x = np.array([1,2,3])

In [90]:
x.shape

(3,)

In [92]:
x.reshape((1,3)).shape

(1, 3)

In [94]:
x = np.array([[1,2], [3,4]])

In [95]:
x

array([[1, 2],
       [3, 4]])

In [96]:
x.T

array([[1, 3],
       [2, 4]])

### Array Concatenation and Splitting 

In [98]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [101]:
np.concatenate((x,y), axis = 0)

array([1, 2, 3, 3, 2, 1])

In [103]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [104]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [111]:
#vstack
x = np.array([1,2,3])
grid = np.random.randint(0, 10, size=(2, 3))

In [ ]:
np.vstack((x, grid))    #Vertical stack

array([[1, 2, 3],
       [3, 2, 0],
       [8, 8, 3]])

In [118]:
y = np.array([[99], 
                [99]])
np.hstack((y, grid))

array([[99, 99],
       [99, 99]])

### Splitting of Arrays

In [119]:
x = np.array([1,2,3,99,69,3,2,1])

In [120]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

In [121]:
x1

array([ 2,  3,  3, 18, 14,  3], dtype=int32)

### Broadcasting and Vectorized operations

In [122]:
a = np.arange(3)

In [123]:
a

array([0, 1, 2])

In [125]:
a + 5 #Broadcasting

array([5, 6, 7])

In [126]:
b = np.ones([3,3])

In [127]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
a.shape, b.shape

((3,), (3, 3))

In [129]:
b + a 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [130]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [131]:
c = np.arange(3).reshape((3,1))

In [132]:
c

array([[0],
       [1],
       [2]])

In [133]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays

In [134]:
list_number = [1,2,3]

In [135]:
ll = np.array(list_number)

In [136]:
ll

array([1, 2, 3])

In [138]:
sum(ll)

np.int64(6)

In [139]:
np.sum(ll)

np.int64(6)

In [143]:
# Create a massive Numpy Array

massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [146]:
%timeit sum(massive_array)

1.97 ms ± 889 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [147]:
%timeit np.sum(massive_array)

13.1 μs ± 1.38 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [148]:
np.mean(massive_array)

np.float64(0.5049999495707101)

In [149]:
np.max(massive_array)

np.float64(0.999685002639177)

In [150]:
np.min(massive_array)

np.float64(0.0002078643980524264)

In [151]:
dog_height = [600, 470, 170, 430, 300]

In [152]:
dog_height = np.array(dog_height)

In [153]:
np.std(dog_height)

np.float64(147.32277488562318)

In [155]:
np.var(dog_height)

np.float64(21704.0)

In [156]:
np.sqrt(np.var(dog_height))

np.float64(147.32277488562318)

### Sorting arrays

In [158]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [160]:
# A related function is argsort, which instead returns the indices of the sorted elements
np.argsort(x)

array([1, 0, 3, 2, 4])

### Sorting along rows or columns

In [162]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size=(4,6))

In [163]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [164]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [165]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

### Linear Algebra

In [166]:
A = np.array([[1,2,3,], 
              [4,5,6], 
              [7,8,9]])
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [167]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [169]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [170]:
B.T @ A 

array([[36, 48, 60],
       [24, 33, 42]])

### Dot product example

In [172]:
np.random.seed(0)

sale_amounts = np.random.randint(0, 20, size=(5,3))

In [173]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [175]:
# Create weekly_sales DataFrame
import pandas as pd 
weekly_sale = pd.DataFrame(sale_amounts, index = ["Mon", "Tue", "Web", "Thu", "Fri"],
                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [176]:
weekly_sale

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Web              9             19             18
Thu              4              6             12
Fri              1              6              7

In [178]:
# Create a price array 
prices = np.array([10, 8, 12])

In [190]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [191]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [192]:
weekly_sale.shape, butter_prices.shape

((5, 3), (1, 3))

In [194]:
total_prices = weekly_sale.dot(butter_prices.T)

In [195]:
total_prices

Price
Mon    240
Tue    138
Web    458
Thu    232
Fri    142

In [196]:
weekly_sale["Total Price"] = total_prices

In [197]:
weekly_sale

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon             12             15              0          240
Tue              3              3              7          138
Web              9             19             18          458
Thu              4              6             12          232
Fri              1              6              7          142